### ISSUE TITLE
Solution explorer shows negative number of projects in solution

### ISSUE THREAD

**Issue by quomat** [reduckted/ProjectFilter#1] opened 2021-05-26 00:04 UTC
Hello,
I encountered a bug, but maybe it's Visual Studio's fault and not this extension's. But I figured it's better to start here.

**Steps to reproduce:**

1. Create new solution, and two projects inside: _Project1_ and _Project2_.
2. Make a reference to Project2 in Project1.
3. "Filter projects"
4. In the pop-up window, deselect Project2
5. Ensure that the button "Load dependencies of selected objects" is active.
6. OK

**Expected behaviour:**
Nothing changes.

**Outcome:**
In the solution item, it says "2 of 1 project".

If we repeat this procedure a few more times, we will get negative number of projects ("2 of -3 projects")

![image](https://user-images.githubusercontent.com/84818106/119583270-835cbf80-bdc6-11eb-9916-41cdfe7031fb.png)

**Comment by reduckted** [comment] 2021-05-28 11:21
Hi, thanks for reporting this. I can reproduce this as well.  As far as I can tell, this is a bug in Visual Studio. I've reported the bug at Developer Community, but I'll leave this issue open just in case it's something caused by the extension.

https://developercommunity.visualstudio.com/t/project-count-in-solution-explorer-is-wrong-after/1435652

**Comment by hguptauk** [comment] 2022-05-20 00:37
Hi, This is really good tool for quickly loading and unloading a projects. Is it possible to extend this to include two checkbox for each project. other checkbox is to also select that projects in multiple start-up project configuration. It will be very useful feature.

**Comment by reduckted** [comment] 2022-10-09 10:40
The upstream issue has been [closed, and will not be fixed](https://developercommunity.visualstudio.com/t/Project-count-in-solution-explorer-is-wr/1435652#TPIN-N10167176) by the Visual Studio team, so I'm going to close this one off as well since there's nothing I can do about it.

**Closed as completed by reduckted** 2022-10-09 10:40 UTC
