### ISSUE TITLE
Project count is wrong when unloading and loading more projects than previously loaded

### ISSUE THREAD

**Issue by Swepps** [reduckted/ProjectFilter#3] opened 2023-07-19 15:58 UTC
I'll preface this by saying that I love this extension, nice job!

To replicate:

- Use latest Visual Studio 2022
- Have one or more projects loaded
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/d8bc2675-232c-4c26-9491-d3b3f8138727)
- Filter projects to unload previous projects and load more projects than were previously loaded
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/0fe72b19-e821-49a5-9b74-e933c2ca2b2d)
- Notice how the project count has decreased
![image](https://github.com/reduckted/ProjectFilter/assets/5452934/d96223ed-774e-4b4b-b30f-3e5f4d64eeef)

Additionally, there are some issues when using the extension with Solution Filter files (.slnf) whereby doing the aforementioned loading/unloading will sometimes hide projects after loading them.

**Comment by reduckted** [comment] 2023-07-24 10:16
Thanks for reporting. 

The project count issue is a duplicate of #1. If you do it enough, the project count eventually becomes negative! Unfortunately it appears to be out of my control and the Visual Studio team  have decided [not to fix it ](https://developercommunity.visualstudio.com/t/Project-count-in-solution-explorer-is-wr/1435652#TPIN-N10167176). 😞 

> Additionally, there are some issues when using the extension with Solution Filter files (.slnf) whereby doing the aforementioned loading/unloading will sometimes hide projects after loading them.

Would you be able to log a new issue with some more information about this? Ideally with some reproduction steps.

Thanks.

**Closed as completed by reduckted** 2023-07-24 10:16 UTC

**Comment by Swepps** [comment] 2023-07-24 10:38
Apologies. I should've checked the closed issues before reporting that first one!
